//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentACar.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Arac
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Arac()
        {
            this.Rezervasyon = new HashSet<Rezervasyon>();
        }

        public int AracId { get; set; }
        [DisplayName("Marka")]
        [Required(ErrorMessage = " boş bırakılamaz")]
        public Nullable<int> MarkaID { get; set; }
        [DisplayName("Model")]
        [Required(ErrorMessage = "  boş bırakılamaz")]
        public Nullable<int> ModelID { get; set; }
        [DisplayName("Tip")]
        [Required(ErrorMessage = " boş bırakılamaz")]
        public Nullable<int> TipID { get; set; }
        [DisplayName("Plaka")]
        [Required(ErrorMessage = "boş bırakılamaz")]
        public string Plaka { get; set; }
        [DisplayName("Şasi Numarası")]
        [Required(ErrorMessage = "boş bırakılamaz")]
        public string SasiNo { get; set; }
        [DisplayName("Renk")]
        [Required(ErrorMessage = "boş bıraklımaz")]
        public string Renk { get; set; }
        [DisplayName("Model Yılı")]
        [Required(ErrorMessage = "boş bıraklımaz")]
        public string ModelYıl { get; set; }
        [DisplayName("Araç Ücreti")]
        [Required(ErrorMessage = " boş bıraklamaz")]
        public Nullable<decimal> GunlukUcret { get; set; }
        [DisplayName("Ödeme Cinsi")]
        [Required(ErrorMessage = " boş bırakılamaz")]
        public string GunlukUcretBirimi { get; set; }
    
        public virtual Marka Marka { get; set; }
        public virtual Model Model { get; set; }
        public virtual Tip Tip { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rezervasyon> Rezervasyon { get; set; }
    }
}
