//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentACar.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Musteri
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Musteri()
        {
            this.Rezervasyon = new HashSet<Rezervasyon>();
        }
    
        public int MusteriId { get; set; }

        [DisplayName("Adý Soyadý")]
        [Required(ErrorMessage = "boþ býrakýlamaz.")]
        public string AdiSoyadi { get; set; }

        [DisplayName("Ünvan")]
        public string Unvan { get; set; }

        [Required(ErrorMessage = "boþ býrakýlamaz.")]
        public string Cinsiyet { get; set; }

        [DisplayName("Doðum Tarihi")]
        public Nullable<System.DateTime> Dogumtarihi { get; set; }

        [DisplayName("TC Kimlik Numarasý")]
        [Required(ErrorMessage = "boþ býrakýlamaz.")]
        public string Tc { get; set; }

        [DisplayName("Vergi Numarasý")]
        [Required(ErrorMessage = "boþ býrakýlamaz.")]
        public string VergiNo { get; set; }

        [DisplayName("Vergi Dairesi")]
        public string VergiDairesi { get; set; }

        [Required(ErrorMessage = "boþ býrakýlamaz.")]
        public string Adres { get; set; }

        [DisplayName("Ev Telefonu")]
        [Required(ErrorMessage = "boþ býrakýlamaz.")]
        public string EvTel { get; set; }

        [DisplayName("Ýþ Telefonu")]
        public string istel { get; set; }

        [DisplayName("Cep Telefonu")]
        [Required(ErrorMessage = "boþ býrakýlamaz.")]
        public string gsm { get; set; }

        [DisplayName("ÝLÇE")]
        [Required(ErrorMessage = "boþ býrakýlamaz.")]
        public Nullable<int> ilceID { get; set; }

        [DisplayName("ÝL")]
        [Required(ErrorMessage = "boþ býrakýlamaz.")]
        public Nullable<int> SehirID { get; set; }
    
        public virtual ilceler ilceler { get; set; }
        public virtual iller iller { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rezervasyon> Rezervasyon { get; set; }
    }
}
